# Generated by Django 5.1.1 on 2024-10-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='course_list',
            field=models.CharField(default='', max_length=400),
        ),
    ]
