# Generated by Django 5.1.1 on 2024-10-24 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_coursemodel_course_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursemodel',
            old_name='course_list',
            new_name='course_link',
        ),
    ]
