# Generated by Django 5.1.1 on 2024-10-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=50)),
                ('subject', models.CharField(default='', max_length=100)),
                ('message', models.TextField(default='', max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
