# Generated by Django 5.1.1 on 2024-10-30 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrolmodel',
            name='transaction_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
